### ISSUE TITLE
setup.py should not pin specific versions

### ISSUE THREAD

**Issue by m000** [regulaforensics/FaceSDK-web-python-client#38]
`install_requires` in setyp.py pins specific versions of several packages. This causes problems when managing package versions in the python environment where FaceSDK is used.

E.g. `certifi==2020.12.5` forces all packages in the environment to use old root certificates. And e.g. Sentry SDK already requires `urllib3>1.26.5`, creating a conflict.

https://github.com/regulaforensics/FaceSDK-web-python-client/blob/1c1529ce86d1db39f7e0fb38745aee25419a603e/setup.py#L20-L26

`install_requires` should be more flexible in allowing FaceSDK to work with more recent versions of the package.

**Comment by m000** [comment]
See also: regulaforensics/DocumentReader-web-python-client#68

**Comment by jurrian** [comment]
This is really affecting us because other packages cannot be updated as a result. The Regula documentreader and facesdk are now conflicting when either one dictates a higher certifi requirement.

**Comment by m000** [comment]
Hey @dangost. Any updates on switching to more flexible requirements specification?

We have 68 top-level dependncies for our production environment. The Regula packages are the only ones we have to handle specially because of the hardcoded dependencies.

**Comment by m000** [comment]
`future==0.18.2` is now also considered vulnerable. See: https://pyup.io/v/52510/f17/

Please do the sane thing and use the [caret or the tilde](https://python-poetry.org/docs/dependency-specification/) to properly constraint versions, instead of pinning specific versions.

**Comment by GubinAlexander** [comment]
Hello @m000 @jurrian 
This issue has been fixed in current 6.9.3 release version. Please feel free to update and use it
